# Generated by Django 2.1.3 on 2018-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Другое'), (7, 'Собака'), (16, 'Кот')], default=0)),
            ],
            options={
                'verbose_name': 'Обитатель приюта',
                'verbose_name_plural': 'Обитатели приюта',
            },
        ),
    ]
