# Generated by Django 2.1.3 on 2018-11-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20181110_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
