# Generated by Django 2.1.3 on 2018-11-10 14:08

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20181110_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakePet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', app.utils.fields.ResizeImageField(blank=True, null=True, upload_to='fake_pets_photo')),
            ],
            options={
                'verbose_name': 'Фото для поиска похожих обитателей приюта',
                'verbose_name_plural': 'Фото для поиска похожих обитателей приюта',
            },
        ),
    ]
