PET_POINT_DEFAULT = 0
PET_POINT_CASH_BOX = 7
PET_POINT_COLLECTION_POINT = 16

PET_POINT_TYPES = (
    (PET_POINT_DEFAULT, 'Стандартная точка'),
    (PET_POINT_CASH_BOX, 'Кэш-бокс'),
    (PET_POINT_COLLECTION_POINT, 'Пункт сбора')
)
